apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  type: LoadBalancer  # Change to ClusterIP if you don't need external access
  selector:
    app: my-nginx  # Match the labels of the Deployment
  ports:
    - port: 80        # Port exposed by the service
      targetPort: 80  # Port on the container
